version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  version: 2
  filter-and-trigger:
    jobs:
      - path-filtering/filter:
          name: check-test-list-change
          base-revision: main
          config-path: .circleci/continue.yml
          mapping: |
            test_list.py run-tests true
